<?php
/**
 * @file sandbox.module
 * Demonstrates the addition of a new pane to the checkout system.
 */

/**
 * Implements hook_commerce_checkout_pane_info().
 */
function sandbox_commerce_checkout_pane_info() {

  $panes['paper_gift'] = array(
    'title' => t('Paper gifts'),
    'base' => 'paper_gift_pane',
    'page' => 'checkout',
    'weight' => -5,
  );

  return $panes;
}

/**
 * Defines a list of default paper gifts to use.
 */
function paper_gift_pane_default_paper_gifts() {
  return array(
    'boy' => t('Boys'),
    'girl' => t('Girls'),
    'christmas' => t('Christmas'),
    'birthday' => t('Birthday'),
    'none' => t('None'),
  );
}

/**
 * Pane: settings form callback.
 */
function paper_gift_pane_settings_form($checkout_pane) {

  $form['paper_gifts'] = array(
    '#type' => 'checkboxes',
    '#title' => t('Ship this item in a gift box'),
    '#default_value' => variable_get('paper_gifts', array()),
    '#options' => paper_gift_pane_default_paper_gifts(),
  );

  return $form;
}

/**
 * Pane: form callback.
 */
function paper_gift_pane_checkout_form($form, &$form_state, $checkout_pane, $order) {
  $paper_gifts = array();
  $default_paper_gifts = paper_gift_pane_default_paper_gifts();

  foreach ($default_paper_gifts as $name => $title) {
    $image = array(
      'path' => drupal_get_path('module', 'sandbox') . '/images/' . $name . '.jpg',
      'title' => $title,
      'alt' => $title,
    );
    $paper_gifts[$name] = theme('image', $image);
  }

  $pane_form['paper_gift'] = array(
    '#type' => 'radios',
    '#default_value' => 'none',
    '#title' => t('Select your paper gift'),
    '#description' => t('Your items will be shipped in a gift box.'),
    '#options' => $paper_gifts,
    '#attributes' => array('class' => array('paper-gift-pane-selection')),
  );

  $pane_form['paper_gift']['#attached']['css'] = array(
    drupal_get_path('module', 'sandbox') . '/css/sandbox.css',
  );

  return $pane_form;
}

/**
 * Pane: form validation callback.
 */
function paper_gift_pane_checkout_form_validate($form, &$form_state, $checkout_pane, $order) {
  // Validate the given value or set to none if null.
  if (!empty($form_state['values'][$checkout_pane['pane_id']])) {
    $pane_values = $form_state['values'][$checkout_pane['pane_id']];

    if (empty($pane_values['paper_gift'])) {
      $pane_values['paper_gift'] = 'none';
    }
  }
  return TRUE;
}

/**
 * Pane: form submission callback.
 */
function paper_gift_pane_checkout_form_submit($form, &$form_state, $checkout_pane, $order) {
  if (!empty($form_state['values'][$checkout_pane['pane_id']])) {
    $pane_values = $form_state['values'][$checkout_pane['pane_id']];
    if (!empty($pane_values['paper_gift'])) {
      $order->data['paper_gift'] = $pane_values['paper_gift'];
    }
  }
}


/**
 * Pane: Review
 */
function paper_gift_pane_review($form, $form_state, $checkout_pane, $order) {
  if ($order->data['paper_gift'] && $order->data['paper_gift']  != 'none') {
    $content['paper_gift'] = array(
      '#type' => 'item',
      '#markup' => t('Items in your order will be wrapped with the %paper paper gift', array('%paper' => $order->data['paper_gift'])),
    );
    return drupal_render($content);
  }
}